name: Run

on:
  workflow_dispatch:
  schedule:
    - cron: "42 2 * * *"

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Python
        uses: actions/setup-python@v1
        with:
          python-version: "3.11"
          architecture: x64
      - uses: actions/checkout@master
      - uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-
      - run: python -m pip install -r requirements.txt
      - name: Set Global Git Config
        run: |
          git config --global user.name 'Oswald Maskens'
          git config --global user.email 'OzieGamma@users.noreply.github.com'
          git config --global init.defaultBranch main

      - name: push to `legifrance` repo
        run: |
          git clone https://OzieGamma:${{ secrets.PAT_PUSH_LEGIFRANCE }}@github.com/LexHub-project/legifrance.git ./output

      - run: python main.py -t
        env:
          CLIENT_ID: ${{ secrets.CLIENT_ID }}
          CLIENT_SECRET: ${{ secrets.CLIENT_SECRET }}

      - name: push to `legifrance` repo
        working-directory: ./output
        run: |
          git push origin main -f

      - run: git status
      - name: Commit cache
        run: |
          echo "$(date)" >| ./cache/last_gh_actions_run
          git add ./cache
          git commit -am "(chore) update cache"
          git push
